spring:
  application:
    name: CarMatchAI
  
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/carmatch
    username: carmatch_user
    password: secret
    driver-class-name: org.postgresql.Driver
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          time_zone: UTC
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

# Server configuration
server:
  port: 8081
  servlet:
    context-path: /

# Logging configuration
logging:
  level:
    ai.carmatch: INFO
    org.springframework.cache: DEBUG
    org.hibernate.SQL: WARN
    org.springframework.jdbc.datasource.init.ScriptUtils: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# JWT configuration
app:
  jwt:
    secret: "anfisa"
    expirationMs: 3600000 # 1 hour

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
